# --- !Ups

create table "STATISTIC" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "URL" varchar not null,
  "SUCCESSFUL" BOOLEAN not null
);

create table "FUND" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "NAME" varchar not null,
  "URL" varchar not null,
  "VERIFIED" BOOLEAN not null
);

create table "DEAL" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "NAME" varchar not null,
  "URL" varchar not null,
  "VERIFIED" BOOLEAN not null
);

create table "FUND_DEAL" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "FUND_ID" bigint not null,
  "DEAL_ID" bigint not null,
  "VERIFIED" BOOLEAN not null,
  "DETAILS" VARCHAR(MAX) not NULL
);

create table "USER" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "USERNAME" varchar not null,
  "PASSWORD" varchar not null
);

# --- !Downs
DROP TABLE "STATISTIC" if EXISTS ;

drop table "FUND" if exists;

drop table "DEAL" if exists;

drop table "FUND_DEAL" if exists;

drop table "USER" if exists;